# -*- coding: utf-8 -*-
"""IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-y0z7f4aFE_bPMcgsmdkCXyN-m1uagEy
"""

# Instala la librería OpenAI actualizada
!pip install --upgrade openai

import openai
from openai import OpenAI

# Pega tu clave secreta de API entre comillas
client = OpenAI(api_key="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")

# Información base del negocio
contexto_base = """
Sos un asistente virtual de una agencia de marketing llamada 'Agencia Creativa Mendoza'.
Ayudás a responder preguntas sobre servicios, horarios, precios y contacto.
Tu tono es profesional, claro y amigable.
"""

print("🤖 Asistente Agencia Creativa Mendoza. Escribí 'salir' para terminar.")

while True:
    pregunta = input("Cliente: ")
    if pregunta.lower() == "salir":
        print("Asistente: ¡Gracias por tu consulta!")
        break

    respuesta = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": contexto_base},
            {"role": "user", "content": pregunta}
        ]
    )

    print("Asistente:", respuesta.choices[0].message.content)